CREATE DATABASE IF NOT EXISTS antonius;

USE antonius;

CREATE TABLE IF NOT EXISTS amtstitelt
(
ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Amtstitel TINYTEXT
);

CREATE TABLE IF NOT EXISTS anredet
(
ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Anrede TINYTEXT
);

CREATE TABLE IF NOT EXISTS abonnentent
(
ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Anrede BIGINT UNSIGNED,
TitelVorgestellt TINYTEXT,
Titelnachgestellt TINYTEXT,
Amtstitel BIGINT UNSIGNED,
Nachname TINYTEXT,
Vorname TINYTEXT,
Organisation TINYTEXT,
Straße TINYTEXT,
Land TINYTEXT,
PLZaustria BIGINT UNSIGNED,
Ortaustria BIGINT UNSIGNED,
PLZallgemein TINYTEXT,
Ortallgemein TINYTEXT,
Antoniusanzahl INT UNSIGNED NOT NULL,
TelNr TINYTEXT,
Mobil TINYTEXT,
EMail TINYTEXT,
Status BIGINT UNSIGNED,
Anmerkungen TEXT,
Dankschreiben BOOLEAN,
letzteÄnderung DATETIME,
Zusatzinformation TINYTEXT,
erstelltAm DATETIME,
StatusGesetztAm DATETIME,
BerufTätigkeit TINYTEXT,
Mietcode TINYTEXT
);

CREATE TABLE IF NOT EXISTS buchungent
(
BuchungsID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
ÜberweiserID BIGINT UNSIGNED,
Buchungsnummer TINYTEXT,
IBAN TINYTEXT,
BIC TINYTEXT,
Datum DATE,
Status TINYTEXT,
GegKto TINYTEXT,
Verwendungszweck TINYTEXT,
Betrag DECIMAL(12,2),
Eingehend BOOLEAN,
Dankbrief BOOLEAN,
letzteÄnderung DATETIME
);

CREATE TABLE IF NOT EXISTS ortaustriat
(
ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Ort TINYTEXT
);

CREATE TABLE IF NOT EXISTS plzaustriat
(
ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
PLZ TINYTEXT
);

CREATE TABLE IF NOT EXISTS plztoortaustriajunct
(
PLZID BIGINT UNSIGNED NOT NULL,
OrtID BIGINT UNSIGNED NOT NULL,
PRIMARY KEY(PLZID, OrtID)
);

CREATE TABLE IF NOT EXISTS statust
(
ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Status TINYTEXT
);

CREATE USER IF NOT EXISTS Sal@localhost IDENTIFIED BY 'insert-your-password-here';
GRANT ALL PRIVILEGES ON antonius.* TO Sal@localhost;
